(define (problem carregarLampada)
(:domain manutencao)
(:objects Sala1 Corredor Deposito Lampada)
(:init (Em Corredor)
	(Sala Sala1)
	(Corredor Corredor)
	(Deposito Deposito)
	(Lampada Lampada)
(:goal (and (Em Sala1) (Com Lampada)))))