(define (problem trocarLampada)
(:domain manutencao)
(:objects Sala1 Sala2 Sala3 Sala4 Corredor Deposito Escada Lampada)
(:init (Em Corredor)
	(Chao Corredor)
	(Corredor Corredor)
	(Sala Sala1)
	(Queimada Sala1)
	(Sala Sala2)
	(Queimada Sala2)
	(Sala Sala3)
	(Queimada Sala3)
	(Sala Sala4)
	(Queimada Sala4)
	(Deposito Deposito)
	(Escada Escada)
	(Lampada Lampada)
(:goal (and (Em Corredor) (Chao Corredor) (Ligada Sala1) (Ligada Sala2) (Ligada Sala3) (Ligada Sala4) )))