(define (problem trocarLampada)
(:domain manutencao)
(:objects Sala1 Corredor Deposito Escada Lampada)
(:init (Em Corredor)
	(Sala Sala1)
	(Queimada Sala1)
	(Corredor Corredor)
	(Deposito Deposito)
	(Escada Escada)
	(Chao Escada)
	(Lampada Lampada)
(:goal (and (Ligada Sala1) (Em Corredor))))